### ISSUE TITLE
Translation error "platform"/"operating system"?

### ISSUE THREAD

**Issue by fuf42** [iobroker-community-adapters/ioBroker.info#107]
Hi,

my info tab displays two times "Betriebssystem".
I think, that this is a translation error and one of the "Betriebssystem"'s should be "Platform"

![grafik](https://user-images.githubusercontent.com/5921063/83612192-5f371b80-a582-11ea-9d0b-8884a95109f8.png)

This is shown, when language is set to english:

![grafik](https://user-images.githubusercontent.com/5921063/83612856-4418db80-a583-11ea-9fa1-02bb7f55498f.png)

This happens on my Zotac zbox Cl-327 with ubuntu 18.04.04, native iobroker install.

I haven't seen this on a ESXi VM (same setup) and on a test raspberry pi.

**Versions:**  
 - Adapter version: 1.7.4
 - JS-Controller version: 3.1.4
 - Node version: v12.17.0
 - Operating system: ubuntu 18.04 LTS

regards,
Christian

**Comment by ldittmar81** [comment]
Done with 1.7.6
