### ISSUE TITLE
does not show adapters available for updating.

### ISSUE THREAD

**Issue by Anzic23** [iobroker-community-adapters/ioBroker.info#116]
The info page says that all adapters are updated. And there are updates on the page with adapters.
![image](https://user-images.githubusercontent.com/37106885/87123918-5b3c9e80-c290-11ea-98d9-ef10c7b7d42a.png)

---

**System data:**

Model: Intel(R) Celeron(R) CPU G1610T @ 2.30GHz
RAM: 9.73 GB
Node.js: v12.18.2
NPM: 6.14.5
Platform: linux
Distribution: Debian GNU/Linux
Architecture: x64
Model: ARMv7 Processor rev 4 (v7l)
RAM: 975.6 MB
Node.js: v12.18.1
NPM: 6.14.5
JS-Controller (1): 3.1.6
Information tab: 1.7.5

> *created by ioBroker.info*

**Comment by Ilovegym66** [comment]
here the same, checked with different browsers ( chrome, firefox, at windows, linux ) and cleaned the cache. Looks like the info-adapter get no message about the updates from admin?
Logfile with debug say everthing fine, no faults seen.

**Comment by ldittmar81** [comment]
Wich Admin version? Are there some errors on the browser console?

**Comment by Ilovegym66** [comment]
Admin 4.1.1, js-controller 3.1.6. I mean with 3.1.4 and info 1.7.2 is running, must check this with a old vm... can that be?

**Comment by Ilovegym66** [comment]
I've updated an old VM from js-controller 2.2.8 with Admin 4.0.5 and info-adapter 1.5.7 step by step, first upgrade node8 to 12, works fine. Next upgrade js-controller to 3.1.6, works fine. Next upgraded info-adapter to 1.7.5, and it works fine.
Here we are now on Admin 4.0.5...  updated.. to 4.1.1.works fine.. I can't reproduce it.
On my productiv system:
![grafik](https://user-images.githubusercontent.com/36229898/87461092-33da2e80-c60e-11ea-93c9-03a9e3b129db.png)
