### ISSUE TITLE
Fehlermeldung nach update auf V 1.1.3

### ISSUE THREAD

**Issue by sigi2345** [iobroker-community-adapters/ioBroker.info#17]
`

info.0 | 2019-03-01 09:37:52.778 | error | TypeError: Converting circular structure to JSON
-- | -- | -- | --
info.0 | 2019-03-01 09:37:52.777 | info | News feed readed...

`

**Comment by ldittmar81** [comment]
Whaaaaat??? It can not be! I commented out the call of the function. Hmm ... can you please try to delete the adapter and reinstall? And thanks for the feedback :+1:

**Comment by sigi2345** [comment]
Schaut gut aus.......

`

  |   |   |  
-- | -- | -- | --
info.0 | 2019-03-01 10:36:33.316 | debug | system.adapter.admin.0: logging true
info.0 | 2019-03-01 10:34:36.882 | debug | system.adapter.admin.0: logging false
info.0 | 2019-03-01 10:33:59.057 | debug | system.adapter.admin.0: logging true
info.0 | 2019-03-01 10:33:51.816 | info | starting. Version 1.1.3 in C:/ioBroker/node_modules/iobroker.info, node: v8.15.0
info.0 | 2019-03-01 10:33:51.801 | debug | statesDB connected
info.0 | 2019-03-01 10:33:51.774 | debug | objectDB connected
info.0 | 2019-03-01 10:33:48.642 | debug | system.adapter.admin.0: logging false
info.0 | 2019-03-01 10:33:29.602 | debug | system.adapter.admin.0: logging true
info.0 | 2019-03-01 10:33:27.969 | info | starting. Version 1.1.3 in C:/ioBroker/node_modules/iobroker.info, node: v8.15.0
info.0 | 2019-03-01 10:33:27.937 | debug | statesDB connected
info.0 | 2019-03-01 10:33:27.937 | debug | objectDB connected
info.0 | 2019-03-01 10:32:19.726 | info | starting. Version 1.1.3 in C:/ioBroker/node_modules/iobroker.info, node: v8.15.0

`

![screenshot 2119](https://user-images.githubusercontent.com/41079106/53629429-d2c6dc00-3c0d-11e9-9fa6-e4ca1865fe9b.png)

**Comment by ldittmar81** [comment]
Cool... Danke :clap:

**Comment by sigi2345** [comment]
Konnte den Fehler raus finden, beim starten von ioBroker wurde ein Adapter-Update angezeigt.
(Verwahrungsort ist im latest)
Dieses habe ich gemacht. Da wurde aber die Version **1.1.2** installiert.
Erst mit einen manuellen upload über die Katze wurde 1.1.3 installiert.....

Dies zu Info.
