### ISSUE TITLE
"Update" and "new adapters" for multihost systems

### ISSUE THREAD

**Issue by ldittmar81** [iobroker-community-adapters/ioBroker.info#27]
Add feature for multihost systems.

> *created by ioBroker.info*

**Comment by olli0815** [comment]
not sure but is this related to a future request to collect slave information, too?
If not would it be possible to create a second instance on a slave host?

**Comment by mcm1957** [comment]
This adapter has been deprecated.

So most certainly this this issue will not be solved anymore
