### ISSUE TITLE
Adaptername wird nicht angezeigt 

### ISSUE THREAD

**Issue by MMeinhardt1** [iobroker-community-adapters/ioBroker.info#277]
Hallo,

im Info tab fehlen teilweise die Namen der Adapter für die ein Update verfügbar ist. 

![08B3B5D0-EC97-4C76-B9A6-8B5D2D3ED70B](https://user-images.githubusercontent.com/56205459/116743393-25240300-a9f9-11eb-986c-d201b591a333.png)

**Comment by sven-s-ter** [comment]
Hallo,
kannst Du mir mehr Informationen bereit stellen? Für mich ist aktuell nicht ersichtlich in wiefern es den Bose Adapter betrifft.
VG

**Comment by Apollon77** [comment]
Dies lag an den Adaptern. Bitte bei den relevanrten Adatern (wenn es noch so ost) Issues öffnen.
