### ISSUE TITLE
Admin5 Kompatibilität: Meine Adapter werden nicht angezeigt

### ISSUE THREAD

**Issue by amg666** [iobroker-community-adapters/ioBroker.info#284]
In der Info Übersicht wird die Übersicht "Meine Adapter" nicht angezeigt (bleibt leer und "Kreis" dreht sich)
![grafik](https://user-images.githubusercontent.com/45561610/119234572-f3e9af00-bb2e-11eb-9567-b1bbe50d881e.png)

Admin Adapter 5.0.31
Getestet mit Firefox und Opera
Intel NUC mit VM Debian10
Node.js: v14.17.0
NPM: 6.14.13

**Comment by sigi2345** [comment]
Dito

**Comment by JBSullivan** [comment]
DITO

![image](https://user-images.githubusercontent.com/44617472/119312920-3ae0bd00-bc73-11eb-9cae-ec160a2989c2.png)

**Comment by Tomscloud** [comment]
Bei mir ebenfalls, aktuell admin.0 v5.1.6
![grafik](https://user-images.githubusercontent.com/68244104/120625789-506b9900-c462-11eb-85d7-333900c6e63a.png)

**Comment by Azathoth88** [comment]
Ebenfalls... Allerdings kann ich mich gar nicht erinnern, dass das überhaupt bei mir korrekt funktionierte.
![Beispiel](https://i.imgur.com/YJvwx2F.png)

**Comment by Apollon77** [comment]
still?
