### ISSUE TITLE
wrong value for free diskspace displayed

### ISSUE THREAD

**Issue by chris299** [iobroker-community-adapters/ioBroker.info#286]
**Describe the bug**  
free disk space shows a wrong value

**Expected behavior**  
show the value, the finder shows

**Screenshots & Logfiles**  

![image](https://user-images.githubusercontent.com/33319001/119311257-200d4900-bc71-11eb-9a39-47c79015efe5.png)

![image](https://user-images.githubusercontent.com/33319001/119311357-459a5280-bc71-11eb-8485-6c701dfa3af7.png)

**Versions:**  
 - Adapter version: 1.7.14
 - JS-Controller version: 3.2.16
 - Node version: 12.22.1
 - Operating system: macOS bug sure 11.3.1

**Additional context**  
in addition, in the logfile I see a recurring warning:
"(98599) State "info.0.uuid" has no existing object, this might lead to an error in future versions"
Is this a problem? and how to avoid this?

**Comment by Apollon77** [comment]
Please try GitHub version
