### ISSUE TITLE
Meine Adapter Bereich auf der Info-Seite zeigt Daueranimation

### ISSUE THREAD

**Issue by daniel-lo** [iobroker-community-adapters/ioBroker.info#287]
Problem tritt nur mit der neuen UI (react) auf.

![daueranimat](https://user-images.githubusercontent.com/4311558/119339034-ffed8200-bc90-11eb-9f63-c7ba09d90cd0.png)

**Comment by sigi2345** [comment]
https://github.com/iobroker-community-adapters/ioBroker.info/issues/284
