### ISSUE TITLE
Nach Update des Javascript Adapters auf 5.2.0: Info Adapter Warnmeldungen

### ISSUE THREAD

**Issue by Speedbreaker12** [iobroker-community-adapters/ioBroker.info#307]
Nach Update des Javascript Adapters auf 5.2.0 schmeißt der Info Adapter bei mir jede Menge Warnmeldungen raus:

`
<html><body>

javascript.0 | 2021-07-05 10:57:34.334 | warn | (4327)     at processImmediate (internal/timers.js:461:21)
-- | -- | -- | --
javascript.0 | 2021-07-05 10:57:34.334 | warn | (4327)     at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5555:41)
javascript.0 | 2021-07-05 10:57:34.333 | warn | (4327)     at Object.stateChange (/opt/iobroker/node_modules/iobroker.javascript/main.js:511:128)
javascript.0 | 2021-07-05 10:57:34.325 | warn | (4327) Could not parse value for id  info.0.sysinfo.disks.fsSize.fs1.used_hist into array: Unexpected token ,  in JSON at position 8
javascript.0 | 2021-07-05 10:57:34.325 | warn | (4327)     at processImmediate (internal/timers.js:461:21)
javascript.0 | 2021-07-05 10:57:34.324 | warn | (4327)     at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5555:41)
javascript.0 | 2021-07-05 10:57:34.324 | warn | (4327)     at Object.stateChange (/opt/iobroker/node_modules/iobroker.javascript/main.js:511:79)
javascript.0 | 2021-07-05 10:57:34.322 | warn | (4327) Could not parse value for id  info.0.sysinfo.disks.fsSize.fs1.used_hist into array: Unexpected token ,  in JSON at position 8
javascript.0 | 2021-07-05 10:57:34.315 | warn | (4327)     at processImmediate (internal/timers.js:461:21)
javascript.0 | 2021-07-05 10:57:34.315 | warn | (4327)     at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5555:41)
javascript.0 | 2021-07-05 10:57:34.314 | warn | (4327)     at Object.stateChange (/opt/iobroker/node_modules/iobroker.javascript/main.js:511:128)
javascript.0 | 2021-07-05 10:57:34.313 | warn | (4327) Could not parse value for id  info.0.sysinfo.disks.fsSize.fs0.used_hist into array: Unexpected token ,  in JSON at position 10
javascript.0 | 2021-07-05 10:57:34.312 | warn | (4327)     at processImmediate (internal/timers.js:461:21)
javascript.0 | 2021-07-05 10:57:34.312 | warn | (4327)     at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5555:41)
javascript.0 | 2021-07-05 10:57:34.311 | warn | (4327)     at Object.stateChange (/opt/iobroker/node_modules/iobroker.javascript/main.js:511:79)
javascript.0 | 2021-07-05 10:57:34.284 | warn | (4327) Could not parse value for id  info.0.sysinfo.disks.fsSize.fs0.used_hist into array: Unexpected token ,  in JSON at position 10

</body>
</html>`

Inhalt des angemeckerten Datenpunktes:
`4237189120,4237189120,4237189120,4237189120,4237189120,4235051008,4237189120,4237189120,4237189120,4237189120,4237189120,4237189120,4237189120,4237189120,4237193216,4237193216,4237193216,4237193216,4237193216,4237193216,4237193216,4237193216,4237193216,4237193216,4237197312,4237197312,4237197312,4237197312,4237197312,4237197312`

![fs1](https://user-images.githubusercontent.com/18654629/124448917-37b51280-dd83-11eb-8784-57d7d71901ea.JPG)

Downgrade auf 5.1.3 behebt das Problem.

Admin: 5.1.9
Info: 1.7.15
JS-Controller: 3.2.16
Node: 12.22.2

**Comment by Maja61** [comment]
dito

`javascript.0 2021-07-05 11:06:24.171	warn	at processImmediate (internal/timers.js:461:21)
javascript.0 2021-07-05 11:06:24.170	warn	at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5697:41)
javascript.0 2021-07-05 11:06:24.170	warn	at Object.stateChange (/opt/iobroker/node_modules/iobroker.javascript/main.js:511:128)
javascript.0 2021-07-05 11:06:24.169	warn	Could not parse value for id info.0.sysinfo.disks.fsSize.fs3.used_hist into array: Unexpected token , in JSON at position 10
javascript.0 2021-07-05 11:06:24.168	warn	at processImmediate (internal/timers.js:461:21)
javascript.0 2021-07-05 11:06:24.168	warn	at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5697:41)
javascript.0 2021-07-05 11:06:24.167	warn	at Object.stateChange (/opt/iobroker/node_modules/iobroker.javascript/main.js:511:79)
javascript.0 2021-07-05 11:06:24.166	warn	Could not parse value for id info.0.sysinfo.disks.fsSize.fs3.used_hist into array: Unexpected token , in JSON at position 10
javascript.0 2021-07-05 11:06:24.161	warn	at processImmediate (internal/timers.js:461:21)
javascript.0 2021-07-05 11:06:24.161	warn	at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5697:41)
javascript.0 2021-07-05 11:06:24.160	warn	at Object.stateChange (/opt/iobroker/node_modules/iobroker.javascript/main.js:511:128)
javascript.0 2021-07-05 11:06:24.159	warn	Could not parse value for id info.0.sysinfo.disks.fsSize.fs2.used_hist into array: Unexpected token , in JSON at position 7
javascript.0 2021-07-05 11:06:24.159	warn	at processImmediate (internal/timers.js:461:21)
javascript.0 2021-07-05 11:06:24.158	warn	at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5697:41)
javascript.0 2021-07-05 11:06:24.158	warn	at Object.stateChange (/opt/iobroker/node_modules/iobroker.javascript/main.js:511:79)
javascript.0 2021-07-05 11:06:24.157	warn	Could not parse value for id info.0.sysinfo.disks.fsSize.fs2.used_hist into array: Unexpected token , in JSON at position 7
javascript.0 2021-07-05 11:06:24.156	warn	at processImmediate (internal/timers.js:461:21)
javascript.0 2021-07-05 11:06:24.155	warn	at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5697:41)
javascript.0 2021-07-05 11:06:24.155	warn	at Object.stateChange (/opt/iobroker/node_modules/iobroker.javascript/main.js:511:128)
javascript.0 2021-07-05 11:06:24.154	warn	Could not parse value for id info.0.sysinfo.disks.fsSize.fs1.used_hist into array: Unexpected token , in JSON at position 9
javascript.0 2021-07-05 11:06:24.153	warn	at processImmediate (internal/timers.js:461:21)
javascript.0 2021-07-05 11:06:24.153	warn	at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5697:41)
javascript.0 2021-07-05 11:06:24.152	warn	at Object.stateChange (/opt/iobroker/node_modules/iobroker.javascript/main.js:511:79)
javascript.0 2021-07-05 11:06:24.151	warn	Could not parse value for id info.0.sysinfo.disks.fsSize.fs1.used_hist into array: Unexpected token , in JSON at position 9
javascript.0 2021-07-05 11:06:24.146	warn	at processImmediate (internal/timers.js:461:21)
javascript.0 2021-07-05 11:06:24.146	warn	at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5697:41)
javascript.0 2021-07-05 11:06:24.145	warn	at Object.stateChange (/opt/iobroker/node_modules/iobroker.javascript/main.js:511:128)
javascript.0 2021-07-05 11:06:24.134	warn	Could not parse value for id info.0.sysinfo.disks.fsSize.fs0.used_hist into array: Unexpected token , in JSON at position 10
javascript.0 2021-07-05 11:06:24.134	warn	at processImmediate (internal/timers.js:461:21)
javascript.0 2021-07-05 11:06:24.133	warn	at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5697:41)
javascript.0 2021-07-05 11:06:24.133	warn	at Object.stateChange (/opt/iobroker/node_modules/iobroker.javascript/main.js:511:79)
javascript.0 2021-07-05 11:06:24.131	warn	Could not parse value for id info.0.sysinfo.disks.fsSize.fs0.used_hist into array: Unexpected token , in JSON at position 10
javascript.0 2021-07-05 11:06:16.209	warn	at processImmediate (internal/timers.js:461:21)
javascript.0 2021-07-05 11:06:16.208	warn	at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5697:41)
javascript.0 2021-07-05 11:06:16.208	warn	at Object.stateChange (/opt/iobroker/node_modules/iobroker.javascript/main.js:511:128)
javascript.0 2021-07-05 11:06:16.189	warn	Could not parse value for id info.0.sysinfo.disks.fsSize.fs3.used_hist into array: Unexpected token , in JSON at position 10`

**Comment by Apollon77** [comment]
Please try GitHub version

**Comment by Stefan592** [comment]
Same problem with v5.2.8

<html>
<body>


javascript.0 | 2021-09-01 13:45:36.934 | info | Could not parse value for id javascript.0.Datenpunkte.Config.Absence.Alina into object: Unexpected number in JSON at position 4
-- | -- | -- | --
javascript.0 | 2021-09-01 13:45:36.933 | info | Could not parse value for id javascript.0.Datenpunkte.Config.Absence.Alina into object: Unexpected number in JSON at position 4
javascript.0 | 2021-09-01 13:45:36.916 | info | Start javascript script.js.Automation.RoomFunctions.Alina.Absence


</body>
</html>

![image](https://user-images.githubusercontent.com/14180760/131666040-78739b10-8c40-4938-a494-83658c0db793.png)


Script is working without problems.

**Comment by Stefan592** [comment]
Vielen dank, das Objekt war als "object" angelegt. Nach dem abändern in "String" tritt die Warnung nicht mehr auf.
