### ISSUE TITLE
Deutsch/englisch Mix in PopUp

### ISSUE THREAD

**Issue by JBSullivan** [iobroker-community-adapters/ioBroker.info#309]
Wenn man über das Info Menü ein Adapter Update macht,
wird das PopUp in Deutsch/Englisch Mix angezeigt.

Adapter Version ist 1.9.0

![image](https://user-images.githubusercontent.com/44617472/126346120-dc986a8f-2007-4a12-95bc-221f5037baef.png)

**Comment by guergen1** [comment]
Hier auch:
![grafik](https://user-images.githubusercontent.com/34395245/131244433-bc996b24-4fcb-4108-9ef5-d4853b33febd.png)
Info: 1.9.8
Admin: 5.1.25
js-controller: 3.3.15
node.js: 12.22.5
NPM: 6.14.14

**Comment by Apollon77** [comment]
Will be fixed in next update
