### ISSUE TITLE
Number of event over 200

### ISSUE THREAD

**Issue by Baenker** [iobroker-community-adapters/ioBroker.info#311]
Nach Update auf 1.90 erscheint im log immer wieder

> 

admin.0 | 2021-07-20 21:11:09.956 | info | (454) Subscribe on all states again
-- | -- | -- | --
admin.0 | 2021-07-20 21:10:20.273 | info | (454) Unsubscribe from all states, except system's, because over 3 seconds the number of events is over 200 (in last second 0)

**Comment by Apollon77** [comment]
Sollte aber nur passieren wenn Du Info Adapter offen hast bzw ein Teil des "info.0.*" Baums offen hast oder!?

**Comment by Baenker** [comment]
Denkbar. Kann es nicht mehr genau sagen ob ich den Baum teilweise offen hatte. Ich mache hier erstmal zu und gucke mal was bei der neuen Version passiert.
