### ISSUE TITLE
Background of info adapter does not change with change of the theme

### ISSUE THREAD

**Issue by Feuer-sturm** [iobroker-community-adapters/ioBroker.info#317]
Admin 5.1.14
info Adapter  1.9.4

The background of the info adapter does not change if the theme changed e.g. dark mode enabled

![grafik](https://user-images.githubusercontent.com/25422320/126867687-624dd805-cb25-4a4e-b36e-750916e662cf.png)

**Comment by Feuer-sturm** [comment]
Admin 5.1.28
Info Adapter v1.9.15

@simatec 
With the new version of the info adapter it is possible to switch to the dark theme :-)
After switiching to dark theme the colour of the text does not change. A refresh of the site is necessary. This is the case as well if you switch back from the dark theme to the light theme.

![Animation18](https://user-images.githubusercontent.com/25422320/141370323-cd10c5eb-94dc-42a4-8606-90e50f63a2b5.gif)

**Comment by simatec** [comment]
In the tabs this is currently a general problem in Admin 5.1.28.  Will be fixed by @GermanBluefox in the near future
