### ISSUE TITLE
The size of the text does not fit to the layout

### ISSUE THREAD

**Issue by Feuer-sturm** [iobroker-community-adapters/ioBroker.info#318]
Admin 5.1.14
info Adapter 1.9.4

The size of the text does not fit to the layout

![grafik](https://user-images.githubusercontent.com/25422320/126867748-eca24682-c10d-4a59-90c1-ddb96bff2314.png)

**Comment by Harry-58** [comment]
The same error with the latest Info  Adapter
Info              :1.9.6
Admin          :5.1.15
Node.js        : v14.17.2
NPM            : v6.14.13
js-controller : 3.3.15

![grafik](https://user-images.githubusercontent.com/56926733/127030810-85ee4faa-c1d1-4245-8054-003b0056786f.png)

**Comment by Feuer-sturm** [comment]
Issue still exists
