### ISSUE TITLE
Systeminformationen - CPU Anzeige unglückliche Darstellung

### ISSUE THREAD

**Issue by JBSullivan** [iobroker-community-adapters/ioBroker.info#321]
Info Adapter 1.9.5
Admin 5.1.14

Die Darstellung der CPU Lasten ist etwas unglücklich geraten.

![image](https://user-images.githubusercontent.com/44617472/126889261-22ddca62-ad4b-48c2-8b05-dc5e6442fbc4.png)

**Comment by sigi2345** [comment]
Dito
(Windows System)
