### ISSUE TITLE
CPU Temperatur Info

### ISSUE THREAD

**Issue by sigi2345** [iobroker-community-adapters/ioBroker.info#325]
Hallo,

bekomme diese Info und die Temperatur wird nicht angezeigt.

`
<html>
<body>

info.0 | 2021-07-27 10:06:07.433 | info | State value to set for "info.0.sysinfo.cpu.temperature.max" has to be type "number" but received type "string"
-- | -- | -- | --
info.0 | 2021-07-27 10:06:07.429 | info | State value to set for "info.0.sysinfo.cpu.temperature.main" has to be type "number" but received type "string"
info.0 | 2021-07-27 10:06:01.675 | info | Reading/updating systemdata.
info.0 | 2021-07-27 10:06:01.652 | info | starting. Version 1.9.6 in C:/Program Files/iobroker/Home/node_modules/iobroker.info, node: v12.22.3, js-controller: 3.3.15

</body>
</html>`

![Screenshot (4015)_LI](https://user-images.githubusercontent.com/41079106/127120363-56cd2450-5d2d-4c50-a9e7-81e3f2e00c86.jpg)

`Plattform: Windows
RAM: 16 GB 
Node.js: 12.22.3
NPM: 6.14.13
JS Controller: 3.3.15
Admin: 5.1.15
Web: 3.4.5
Socket.io: 3.1.4
Script Engine: 5.2.8
IOT: 1.8.22
VIS: 1.4.2
HM-Rega: 3.0.29
HM-RPC: 1.14.43
Jarvis: 3.0.0
Backitup: 2.1.12
Cloud: 4.1.0
ICal: 1.10.2
iQontrol: 1.8.0
fb-checkpresence: 1.1.5
Hue: 3.5.19
Alexa2: 3.9.3
Material UI: 1.0.3
E-Charts: 1.0.2
Info: 1.9.6`

**Comment by Apollon77** [comment]
Dann steht die Temperatur nicht zur verfügung, sorry ...
