### ISSUE TITLE
Right side of the clock is hidden in mobile view

### ISSUE THREAD

**Issue by Feuer-sturm** [iobroker-community-adapters/ioBroker.info#326]
Admin 5.1.15
info Adapter 1.9.7

Right side of the clock is hidden by the text area bloc of day and date.
![grafik](https://user-images.githubusercontent.com/25422320/127575446-b506d6df-4e01-4de7-8ae7-5ba7360bcc23.png)

**Comment by Apollon77** [comment]
just cosmetic ... we will not change that
