### ISSUE TITLE
Verfügbare Adapterupdates werden nicht in der INFO angezeigt

### ISSUE THREAD

**Issue by guergen1** [iobroker-community-adapters/ioBroker.info#332]
![grafik](https://user-images.githubusercontent.com/34395245/127735575-93bd161a-5cfe-4cda-ae66-48bb089ff18b.png)
![grafik](https://user-images.githubusercontent.com/34395245/127735581-1304a84a-1a3b-4705-9855-0c239d5a708e.png)

Versions:
    Info-Adapter: 1.9.7
    Admin-Adapter version: 5.1.17
    JS-Controller version: 3.3.15
    Node version: v12.22.4
    NPM Version: 6.14.14

**Comment by guergen1** [comment]
Auch bei Version 1.9.8 ist der Fehler da

**Comment by kkeintzel** [comment]
Bei mir ähnliches Problem: info und ical wurden nicht als Adapter-Updates angezeigt. Nur admin-adapter wird angezeigt, obwohl diese bereits upgedated ist.
Unter ADAPTER wird alles korrekt angezeigt. 
Nicht mal ein iob restart behebt das Issue  
![Bildschirmfoto 2021-08-03 um 11 11 05](https://user-images.githubusercontent.com/83504161/127990142-937a7c36-f71f-4e90-9c09-d63bba39e3f2.png)

**Comment by Voodoo2man** [comment]
Ich habe festgestellt, dass der Info Adapter nicht die Updates zum Host sondern vom Slave anzeigt.
Das Update welches über den Info Adapter gestartet wird, wird auf dem Slave installiert.

**Comment by Apollon77** [comment]
@simatec any idea?

**Comment by simatec** [comment]
@Apollon77 I'll take a look at it and try to fix it.

**Comment by guergen1** [comment]
WLED wurde mir grade in der INFO angezeigt (Info V 1.9.10)

**Comment by guergen1** [comment]
Andere Updates, wie z.B. heute Synology wird nicht angezeigt.

**Comment by guergen1** [comment]
Jetzt habe ich zwei Fenster auf und beide zeigen unterschiedliches an. Hier Fenster 1:
![grafik](https://user-images.githubusercontent.com/34395245/138309205-bff1df5b-4b89-4329-b423-50d0cb783f81.png)
Und hier Fenster 2:
![grafik](https://user-images.githubusercontent.com/34395245/138309275-5a12afca-c60d-46f1-a905-e361501a2c7f.png)

**Comment by Apollon77** [comment]
Still happening?

**Comment by amg666** [comment]
bei mir läuft es seit einiger Zeit ohne Probleme und Updates werden angezeigt
