### ISSUE TITLE
Verfügbare Updates ohne Titel

### ISSUE THREAD

**Issue by daniel-lo** [iobroker-community-adapters/ioBroker.info#333]
Des Öfteren tauchen Updates ohne Adapternamen auf .. diesen sieht man dann im Fortschrittsfenster .. hatte ich z.B. bei MQTT oder beim Web-Adapter

![grafik](https://user-images.githubusercontent.com/4311558/127821980-a093acf6-fed5-40e2-886e-2fae52298d65.png)

**Comment by daniel-lo** [comment]
Nun auch hier:

![grafik](https://user-images.githubusercontent.com/4311558/127876436-62d6ae79-f057-474c-b73c-ed9e65a38b39.png)

**Comment by daniel-lo** [comment]
Doppeltes Tooltip:

![grafik](https://user-images.githubusercontent.com/4311558/127952842-2697fb1f-53fc-43a5-8342-8ec38b37c65d.png)

**Comment by Apollon77** [comment]
Still there?

**Comment by daniel-lo** [comment]
Aktuelle Ansicht .. bei einem "Neuen Adapter" wieder kein Text:

![grafik](https://user-images.githubusercontent.com/4311558/131881061-6598eb75-4571-4f6d-843c-ab8a1a2fa888.png)

Ob bei Aktualisierungen .. kann ich grad nicht sagen .. diese haben ja Text.

**Comment by Apollon77** [comment]
still?

**Comment by daniel-lo** [comment]
yes!

![grafik](https://user-images.githubusercontent.com/4311558/141651754-d2114012-f944-4cd0-af11-9c979189ca0c.png)

**Comment by daniel-lo** [comment]
![grafik](https://user-images.githubusercontent.com/4311558/141921935-9bc165f5-bf3e-4959-82fa-342924064527.png)

**Comment by Apollon77** [comment]
Ok, I fixed it for web ... at leats in it's io-package ... we need to fix every one where it happens

**Comment by daniel-lo** [comment]
The other one was HomeKit .. if I recall correctly

**Comment by Apollon77** [comment]
kk

**Comment by daniel-lo** [comment]
kk?

**Comment by Apollon77** [comment]
Ok, Fixe ich :-)
