### ISSUE TITLE
Wrong Type again

### ISSUE THREAD

**Issue by Speedbreaker12** [iobroker-community-adapters/ioBroker.info#334]
(19574) State value to set for "info.0.sysinfo.network.stats.iface0.tx_sec" has to be stringified but received type "number"

(19574) State value to set for "info.0.sysinfo.cpu.info.cache-l3" has to be type "number" but received type "string"

(19574) State value to set for "info.0.sysinfo.cpu.info.cache-l2" has to be type "number" but received type "string"

(19574) State value to set for "info.0.sysinfo.cpu.info.cache-l1i" has to be type "number" but received type "string"

(19574) State value to set for "info.0.sysinfo.cpu.info.cache-l1d" has to be type "number" but received type "string"

(19574) State value to set for "info.0.sysinfo.cpu.info.speed" has to be type "string" but received type "number"

**Comment by guergen1** [comment]
Hier so ähnlich:
`
<html><body>


 
--
info.0 | 2021-08-07 16:52:42.594 | info | State value to set for "info.0.sysinfo.network.stats.iface0.tx_sec" has to be stringified but received type "number"
info.0 | 2021-08-07 16:52:42.577 | info | State value to set for "info.0.sysinfo.network.stats.iface0.rx_sec" has to be stringified but received type "number"


</body>
</html>`

**Comment by Herbert-Testmann** [comment]
info.0 | 2021-08-09 21:01:32.121 | info | Reading network data every 3 seconds.
-- | -- | -- | --
info.0 | 2021-08-09 21:01:31.000 | info | Reading disk data every 8 seconds.
info.0 | 2021-08-09 21:01:30.505 | info | Reading process data every 8 seconds.
info.0 | 2021-08-09 21:01:29.585 | info | Reading user data every 8 seconds.
info.0 | 2021-08-09 21:01:27.643 | info | Reading battery data every 8 seconds.
info.0 | 2021-08-09 21:01:27.125 | info | Reading memory data every 3 seconds.
info.0 | 2021-08-09 21:01:27.028 | info | Reading CPU current speed every 3 seconds.
info.0 | 2021-08-09 21:01:26.966 | info | Reading CPU temp data every 3 seconds.
info.0 | 2021-08-09 21:01:26.925 | info | cpu Temp res = {"main":64.452,"cores":[],"max":64.452,"socket":[],"chipset":null}
info.0 | 2021-08-09 21:01:26.863 | info | Reading CPU data every 3 seconds.
info.0 | 2021-08-09 21:01:26.666 | info | State value to set for "info.0.sysinfo.cpu.info.cache-l3" has to be type "number" but received type "string"
info.0 | 2021-08-09 21:01:26.651 | info | State value to set for "info.0.sysinfo.cpu.info.cache-l2" has to be type "number" but received type "string"
info.0 | 2021-08-09 21:01:26.636 | info | State value to set for "info.0.sysinfo.cpu.info.cache-l1i" has to be type "number" but received type "string"
info.0 | 2021-08-09 21:01:26.578 | info | State value to set for "info.0.sysinfo.cpu.info.cache-l1d" has to be type "number" but received type "string"
info.0 | 2021-08-09 21:01:26.431 | info | State value to set for "info.0.sysinfo.cpu.info.speed" has to be type "string" but received type "number"
info.0 | 2021-08-09 21:01:25.019 | info | Reading/updating systemdata.
info.0 | 2021-08-09 21:01:24.896 | info | starting. Version 1.9.8 in /opt/iobroker/node_modules/iobroker.info, node: v12.22.1, js-controller: 3.3.15

**Comment by Apollon77** [comment]
Please delete affected objects and restart adapter
