### ISSUE TITLE
Aktualisierungen der "beta" Adapter werden angezeigt, obwohl Einstellungen "stable"

### ISSUE THREAD

**Issue by andreas0022** [iobroker-community-adapters/ioBroker.info#335]
Im Feld "Aktualisierungen" werden auch Adapter angezeigt, welche nur im "beta" sind. Einstellungen sind aber im "stable". Info Adapter V. 1.9.8

**Comment by Apollon77** [comment]
@simatec any idea?

**Comment by simatec** [comment]
@Apollon77 I'll take a look at it and try to fix it.

**Comment by Apollon77** [comment]
@simatec should be fixed in current version?
