### ISSUE TITLE
States are not existing - Warnings in protocoll

### ISSUE THREAD

**Issue by arturDUS** [iobroker-community-adapters/ioBroker.info#336]
Version: 1.9.8
![image](https://user-images.githubusercontent.com/45556368/128608567-26136a84-bbb0-41a9-9d61-342d2bb78461.png)

Every 2 minutes a waring is raised in the protocol which says that some objects are nit existing:
![image](https://user-images.githubusercontent.com/45556368/128607533-eba29c3b-93e3-4cfd-b461-bf96477e95f0.png)

Maybe there is a type in the name of the object. The warning says ist is missing 
info.0.sysinfo.cpu.currentSpeed.coresSpeed
and
info.0.sysinfo.cpu.currentLoad.currentLoad_hist

both are available but with small letters 
in ...current**l**oad_hist and not ...current**L**oad_hist 
![image](https://user-images.githubusercontent.com/45556368/128607798-5019005e-50f6-4446-9eb8-071e6bb3a642.png)

and ...cores**s**peed... and not ...cores**S**peed...
![image](https://user-images.githubusercontent.com/45556368/128607778-5d70cb28-31f6-4542-869a-8ca515be5427.png)

**Comment by Apollon77** [comment]
will be fixed in 1.9.9 soon

**Comment by latzi0710** [comment]
Same behaviour with 1.9.9 (objects deleted)

**Comment by Apollon77** [comment]
@latzi0710 which objects are existing?

**Comment by Speedbreaker12** [comment]
> 
> 
> @latzi0710 which objects are existing?

Same issue as this one: https://github.com/iobroker-community-adapters/ioBroker.info/issues/347

fixed it and made a pull request:
https://github.com/iobroker-community-adapters/ioBroker.info/pull/348

**Comment by latzi0710** [comment]
> @latzi0710 which objects are existing?

![image](https://user-images.githubusercontent.com/59318512/132080163-27bb5c59-aeb3-43cc-a634-9aadd344db80.png)

![image](https://user-images.githubusercontent.com/59318512/132080220-2c1493fd-bb9b-4f3d-a943-96f1350b3d50.png)

**Comment by Apollon77** [comment]
@Speedbreaker12 Interesting ... I changed exactly that because users told that these with the uppercasse chars are not existing (see above in this thread) ... so whats now reality? ;-) @arturDUS ??

**Comment by Speedbreaker12** [comment]
> @Speedbreaker12 Interesting ... I changed exactly that because users told that these with the uppercasse chars are not existing (see above in this thread) ... so whats now reality? ;-) @arturDUS ??

Definitely like in my pull request. I deleted the object tree and checked!

**Comment by Apollon77** [comment]
1.9.10 goes out
