### ISSUE TITLE
after js-controller Update 3.3.15 info messages

### ISSUE THREAD

**Issue by mcuiobroker** [iobroker-community-adapters/ioBroker.info#346]
`
<html>
<body>

info.0 | 2021-09-01 19:03:50.166 | info | State value to set for "info.0.sysinfo.network.stats.iface0.tx_sec" has to be stringified but received type "number"
-- | -- | -- | --
info.0 | 2021-09-01 19:03:50.112 | info | State value to set for "info.0.sysinfo.network.stats.iface0.rx_sec" has to be stringified but received type "number"
info.0 | 2021-09-01 20:48:02.141 | info | cpu Temp res = {"main":47.225,"cores":[],"max":47.225,"socket":[],"chipset":null}
-- | -- | -- | --
info.0 | 2021-09-01 20:48:01.988 | info | State value to set for "info.0.sysinfo.cpu.info.cache-l3" has to be type "number" but received type "string"
info.0 | 2021-09-01 20:48:01.982 | info | State value to set for "info.0.sysinfo.cpu.info.cache-l2" has to be type "number" but received type "string"
info.0 | 2021-09-01 20:48:01.975 | info | State value to set for "info.0.sysinfo.cpu.info.cache-l1i" has to be type "number" but received type "string"
info.0 | 2021-09-01 20:48:01.930 | info | State value to set for "info.0.sysinfo.cpu.info.cache-l1d" has to be type "number" but received type "string"
info.0 | 2021-09-01 20:48:01.794 | info | State value to set for "info.0.sysinfo.cpu.info.speed" has to be type "string" but received type "number"

</body>
</html>`

**Versions:**  
 - Adapter version: 1.9.8
 - JS-Controller version: 3.3.15
 - Node version: 12.22.6
 - Operating system: linux

**Comment by Apollon77** [comment]
Please delete the relevant objects and restart adapter
