### ISSUE TITLE
Warn state "info.0.sysinfo.cpu.currentSpeed.coresspeed

### ISSUE THREAD

**Issue by Marsx79** [iobroker-community-adapters/ioBroker.info#347]
V1.9.9

Das log wird im Sekundentakt mit dieser Meldung geflutet.

2021-09-03 08:01:02.038 | warn | State "info.0.sysinfo.cpu.currentSpeed.coresspeed" has no existing object, this might lead to an error in future versions

**Comment by Speedbreaker12** [comment]
Bei mir das Selbe, zusätzlich noch:
`
<html><body>


info.0 | 2021-09-03 11:09:41.969 | warn | State "info.0.sysinfo.cpu.currentSpeed.coresspeed" has no existing object, this might lead to an error in future versions
-- | -- | -- | --
info.0 | 2021-09-03 11:09:41.379 | warn | State "info.0.sysinfo.cpu.currentLoad.currentload_hist" has no existing object, this might lead to an error in future versions


</body>
</html>`

**Comment by intruder7777** [comment]
bei mir ebenfalls

**Comment by hoak2** [comment]
It says State "info.0.sysinfo.cpu.currentSpeed.coresspeed" has no existing object, this might lead to an error in future versions

The Adapter creates State "info.0.sysinfo.cpu.currentSpeed.cores**S**peed"

Manually creating this states with lower case **s** and the warning is gone
