### ISSUE TITLE
Multihost: Adapter werden nicht mit dem "+" auf dem richtigen Host installiert

### ISSUE THREAD

**Issue by guergen1** [iobroker-community-adapters/ioBroker.info#349]
Multihost-System:
Wenn ich einen Adapter mittels dem "+"-Zeichen auf dem Slave installieren will, muss ich oben den richtigen Host wählen: 
![grafik](https://user-images.githubusercontent.com/34395245/132126995-7f324800-e9e5-4e65-8e58-778ca8ba354c.png)

Die Auswahl hier wird ignoriert:
![grafik](https://user-images.githubusercontent.com/34395245/132126978-fc85ef82-d69a-4166-aec6-ec0d44d19b1c.png)

Das funktioniert m.e. schon länger nicht mehr und hat nichts mit der aktuellen Version zu tun!

**Comment by Apollon77** [comment]
--> Admin Issue.Bitte in aktueller Admin5 version prüfren und ggf dort neu öffnen
