### ISSUE TITLE
Adapter installation

### ISSUE THREAD

**Issue by ggraziotti** [iobroker-community-adapters/ioBroker.info#35]
How to install and after activate the adapter.

On upper left corner, after click, on list I do not see "informazioni" or "information" tab that I have to enable.

Help me please...

**Comment by ldittmar81** [comment]
If you got a intance of iobroker.info, you should see it on the upper left corner.

![13-05-_2019_08-58-02](https://user-images.githubusercontent.com/9552828/57601700-824cf280-755d-11e9-8c6b-268f9d0908a9.png)

![13-05-_2019_08-58-28](https://user-images.githubusercontent.com/9552828/57601709-85e07980-755d-11e9-95ec-0b7c6d98b1bf.png)

**Comment by ggraziotti** [comment]
Tks

Il lun 13 mag 2019, 09:00 ldittmar <notifications@github.com> ha scritto:
