### ISSUE TITLE
LOG Warnings

### ISSUE THREAD

**Issue by jwedenig** [iobroker-community-adapters/ioBroker.info#352]
Many warnings like this
`
<pre class="markdown-highlight" style="font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-indent: 0px; text-transform: none; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; box-sizing: border-box; overflow: auto; font-family: Menlo, Monaco, Consolas, &quot;Courier New&quot;, monospace; font-size: 13px; display: block; padding: 9.5px; margin: 1rem 0px 10px; line-height: 1.42857143; word-break: break-all; word-wrap: break-word; color: rgb(51, 51, 51); background-color: inherit; border: none; border-top-left-radius: 0px; border-top-right-radius: 0px; border-bottom-right-radius: 0px; border-bottom-left-radius: 0px; max-height: 350px; caret-color: rgb(51, 51, 51); text-align: left;"><code class="hljs css" data-lines="1" style="box-sizing: border-box; font-family: Menlo, Monaco, Consolas, &quot;Courier New&quot;, monospace; font-size: inherit; padding: 0.5em; color: rgb(230, 225, 220); background-color: rgb(35, 35, 35); border-top-left-radius: 0px; border-top-right-radius: 0px; border-bottom-right-radius: 0px; border-bottom-left-radius: 0px; white-space: pre; display: inline-block; overflow-x: auto; -webkit-user-select: all; word-wrap: normal; min-width: 100%;">

  | 2021-09-22 09:21:40.273 - warn: info.0 (32378) State "info.0.sysinfo.cpu.currentLoad.currentLoad_hist" has no existing object, this might lead to an error in future versions
-- | --
  | 2021-09-22 09:21:40.461 - warn: info.0 (32378) State "info.0.sysinfo.cpu.currentSpeed.coresSpeed" has no existing object, this might lead to an error in future versions
  | 2021-09-22 09:21:43.273 - warn: info.0 (32378) State "info.0.sysinfo.cpu.currentLoad.currentLoad_hist" has no existing object, this might lead to an error in future versions
  | 2021-09-22 09:21:43.463 - warn: info.0 (32378) State "info.0.sysinfo.cpu.currentSpeed.coresSpeed" has no existing object, this might lead to an error in future versions
  | 2021-09-22 09:21:44.474 - warn: info.0 (32378) State "info.0.sysinfo.battery.hasBattery" has no existing object, this might lead to an error in future versions
  | 2021-09-22 09:21:44.475 - warn: info.0 (32378) State "info.0.sysinfo.battery.cycleCount" has no existing object, this might lead to an error in future versions
  | 2021-09-22 09:21:44.477 - warn: info.0 (32378) State "info.0.sysinfo.battery.isCharging" has no existing object, this might lead to an error in future versions
  | 2021-09-22 09:21:44.478 - warn: info.0 (32378) State "info.0.sysinfo.battery.maxCapacity" has no existing object, this might lead to an error in future versions
  | 2021-09-22 09:21:44.479 - warn: info.0 (32378) State "info.0.sysinfo.battery.currentCapacity" has no existing object, this might lead to an error in future versions
  | 2021-09-22 09:21:44.481 - warn: info.0 (32378) State "info.0.sysinfo.battery.timeRemaining" has no existing object, this might lead to an error in future versions
  | 2021-09-22 09:21:44.493 - warn: info.0 (32378) State "info.0.sysinfo.battery.acConnected" has no existing object, this might lead to an error in future versions
  | 2021-09-22 09:21:46.321 - warn: info.0 (32378) State "info.0.sysinfo.cpu.currentLoad.currentLoad_hist" has no existing object, this might lead to an error in future versions
  | 2021-09-22 09:21:46.471 - warn: info.0 (32378) State "info.0.sysinfo.cpu.currentSpeed.coresSpeed" has no existing object, this might lead to an error in future versions
  | 2021-09-22 09:21:49.274 - warn: info.0 (32378) State "info.0.sysinfo.cpu.currentLoad.currentLoad_hist" has no existing object, this might lead to an error in future versions
  | 2021-09-22 09:21:49.400 - warn: info.0 (32378) State "info.0.sysinfo.cpu.currentSpeed.coresSpeed" has no existing object, this might lead to an error in future versions
  | 2021-09-22 09:21:52.382 - warn: info.0 (32378) State "info.0.sysinfo.cpu.currentLoad.currentLoad_hist" has no existing object, this might lead to an error in future versions
  | 2021-09-22 09:21:52.468 - warn: info.0 (32378) State "info.0.sysinfo.cpu.currentSpeed.coresSpeed" has no existing object, this might lead to an error in future versions
  | 2021-09-22 09:21:52.485 - warn: info.0 (32378) State "info.0.sysinfo.battery.hasBattery" has no existing object, this might lead to an error in future versions
  | 2021-09-22 09:21:52.515 - warn: info.0 (32378) State "info.0.sysinfo.battery.cycleCount" has no existing object, this might lead to an error in future versions
  | 2021-09-22 09:21:52.516 - warn: info.0 (32378) State "info.0.sysinfo.battery.isCharging" has no existing object, this might lead to an error in future versions
  | 2021-09-22 09:21:52.517 - warn: info.0 (32378) State "info.0.sysinfo.battery.maxCapacity" has no existing object, this might lead to an error in future versions
  | 2021-09-22 09:21:52.517 - warn: info.0 (32378) State "info.0.sysinfo.battery.currentCapacity" has no existing object, this might lead to an error in future versions
  | 2021-09-22 09:21:52.518 - warn: info.0 (32378) State "info.0.sysinfo.battery.timeRemaining" has no existing object, this might lead to an error in future versions
  | 2021-09-22 09:21:52.519 - warn: info.0 (32378) State "info.0.sysinfo.battery.acConnected" has no existing object, this might lead to an error in future versions
  | 2021-09-22 09:21:55.333 - warn: info.0 (32378) State "info.0.sysinfo.cpu.currentLoad.currentLoad_hist" has no existing object, this might lead to an error in future versions
  | 2021-09-22 09:21:55.457 - warn: info.0 (32378) State "info.0.sysinfo.cpu.currentSpeed.coresSpeed" has no existing object, this might lead to an error in future versions
  | 2021-09-22 09:21:58.317 - warn: info.0 (32378) State "info.0.sysinfo.cpu.currentLoad.currentLoad_hist" has no existing object, this might lead to an error in future versions
  | 2021-09-22 09:21:58.406 - warn: info.0 (32378) State "info.0.sysinfo.cpu.currentSpeed.coresSpeed" has no existing object, this might lead to an error in future versions
  | 2021-09-22 09:22:00.476 - warn: info.0 (32378) State "info.0.sysinfo.battery.hasBattery" has no existing object, this might lead to an error in future versions
  | 2021-09-22 09:22:00.477 - warn: info.0 (32378) State "info.0.sysinfo.battery.cycleCount" has no existing object, this might lead to an error in future versions
  | 2021-09-22 09:22:00.477 - warn: info.0 (32378) State "info.0.sysinfo.battery.isCharging" has no existing object, this might lead to an error in future versions
  | 2021-09-22 09:22:00.478 - warn: info.0 (32378) State "info.0.sysinfo.battery.maxCapacity" has no existing object, this might lead to an error in future versions
  | 2021-09-22 09:22:00.478 - warn: info.0 (32378) State "info.0.sysinfo.battery.currentCapacity" has no existing object, this might lead to an error in future versions
  | 2021-09-22 09:22:00.479 - warn: info.0 (32378) State "info.0.sysinfo.battery.timeRemaining" has no existing object, this might lead to an error in future versions
  | 2021-09-22 09:22:00.480 - warn: info.0 (32378) State "info.0.sysinfo.battery.acConnected" has no existing object, this might lead to an error in future versions
  | 2021-09-22 09:22:01.327 - warn: info.0 (32378) State "info.0.sysinfo.cpu.currentLoad.currentLoad_hist" has no existing object, this might lead to an error in future versions
  | 2021-09-22 09:22:01.485 - warn: info.0 (32378) State "info.0.sysinfo.cpu.currentSpeed.coresSpeed" has no existing object, this might lead to an error in future versions
  | 2021-09-22 09:22:04.318 - warn: info.0 (32378) State "info.0.sysinfo.cpu.currentLoad.currentLoad_hist" has no existing object, this might lead to an error in future versions
  | 2021-09-22 09:22:04.402 - warn: info.0 (32378) State "info.0.sysinfo.cpu.currentSpeed.coresSpeed" has no existing object, this might lead to an error in future versions
  | 2021-09-22 09:22:07.797 - warn: info.0 (32378) State "info.0.sysinfo.cpu.currentLoad.currentLoad_hist" has no existing object, this might lead to an error in future versions
  | 2021-09-22 09:22:07.799 - warn: info.0 (32378) State "info.0.sysinfo.cpu.currentSpeed.coresSpeed" has no existing object, this might lead to an error in future versions
  | 2021-09-22 09:22:08.475 - warn: info.0 (32378) State "info.0.sysinfo.battery.hasBattery" has no existing object, this might lead to an error in future versions
  | 2021-09-22 09:22:08.476 - warn: info.0 (32378) State "info.0.sysinfo.battery.cycleCount" has no existing object, this might lead to an error in future versions
  | 2021-09-22 09:22:08.477 - warn: info.0 (32378) State "info.0.sysinfo.battery.isCharging" has no existing object, this might lead to an error in future versions
  | 2021-09-22 09:22:08.478 - warn: info.0 (32378) State "info.0.sysinfo.battery.maxCapacity" has no existing object, this might lead to an error in future versions
  | 2021-09-22 09:22:08.478 - warn: info.0 (32378) State "info.0.sysinfo.battery.currentCapacity" has no existing object, this might lead to an error in future versions
  | 2021-09-22 09:22:08.479 - warn: info.0 (32378) State "info.0.sysinfo.battery.timeRemaining" has no existing object, this might lead to an error in future versions
  | 2021-09-22 09:22:08.479 - warn: info.0 (32378) State "info.0.sysinfo.battery.acConnected" has no existing object, this might lead to an error in future versions
  | 2021-09-22 09:22:10.328 - warn: info.0 (32378) State "info.0.sysinfo.cpu.currentLoad.currentLoad_hist" has no existing object, this might lead to an error in future versions
  | 2021-09-22 09:22:10.430 - warn: info.0 (32378) State "info.0.sysinfo.cpu.currentSpeed.coresSpeed" has no existing object, this might lead to an error in future versions
  | 2021-09-22 09:22:13.282 - warn: info.0 (32378) State "info.0.sysinfo.cpu.currentLoad.currentLoad_hist" has no existing object, this might lead to an error in future versions
  | 2021-09-22 09:22:13.430 - warn: info.0 (32378) State "info.0.sysinfo.cpu.currentSpeed.coresSpeed" has no existing object, this might lead to an error in future versions
  | 2021-09-22 09:22:16.282 - warn: info.0 (32378) State "info.0.sysinfo.cpu.currentLoad.currentLoad_hist" has no existing object, this might lead to an error in future versions
  | 2021-09-22 09:22:16.430 - warn: info.0 (32378) State "info.0.sysinfo.cpu.currentSpeed.coresSpeed" has no existing object, this might lead to an error in future versions
  | 2021-09-22 09:22:16.480 - warn: info.0 (32378) State "info.0.sysinfo.battery.hasBattery" has no existing object, this might lead to an error in future versions
  | 2021-09-22 09:22:16.482 - warn: info.0 (32378) State "info.0.sysinfo.battery.cycleCount" has no existing object, this might lead to an error in future versions
  | 2021-09-22 09:22:16.490 - warn: info.0 (32378) State "info.0.sysinfo.battery.isCharging" has no existing object, this might lead to an error in future versions
  | 2021-09-22 09:22:16.491 - warn: info.0 (32378) State "info.0.sysinfo.battery.maxCapacity" has no existing object, this might lead to an error in future versions
  | 2021-09-22 09:22:16.492 - warn: info.0 (32378) State "info.0.sysinfo.battery.currentCapacity" has no existing object, this might lead to an error in future versions
  | 2021-09-22 09:22:16.493 - warn: info.0 (32378) State "info.0.sysinfo.battery.timeRemaining" has no existing object, this might lead to an error in future versions
  | 2021-09-22 09:22:16.493 - warn: info.0 (32378) State "info.0.sysinfo.battery.acConnected" has no existing object, this might lead to an error in future versions

</code></pre>`

Please fix it!
Thanks!!!

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**

**Comment by Apollon77** [comment]
Please check with most current info version
