### ISSUE TITLE
"Rolle" lässt die DP-Liste nicht kleiner(übersichtlicher) werden

### ISSUE THREAD

**Issue by guergen1** [iobroker-community-adapters/ioBroker.info#363]
info: V1.9.10
js-controller: 3.3.18
NPM: 6.14.15
node.js: 12.22.6

Wenn ich unter Rolle z.B. die level.temperature auswähle, wird die Datenpunktliste nicht auf die DP zusammengeschrumpft. Lediglich manche Ordner, die diese Rolle beinhalten werden in einer anderen Farbe dargestellt. Teilweise aber auch Ordner, wo diese Werte gar nicht verfügbar sind angezeigt:
![grafik](https://user-images.githubusercontent.com/34395245/136419742-917d6c86-a06e-4fbe-a138-ecff498eab71.png)

Bei "Zimmer" werden die nicht angesprochenen Ordner und Datenpunkte (nach einer kurzen Zeit) ausgeblendet:
![grafik](https://user-images.githubusercontent.com/34395245/136419154-575734b7-9e9c-4af6-8c95-f78d92108b79.png)

**Comment by Apollon77** [comment]
bitte in neuester Admin Version prüfen und ggf dort Isues checkern undnöffnen
