### ISSUE TITLE
Dependency on hcitool?

### ISSUE THREAD

**Issue by dklinger** [iobroker-community-adapters/ioBroker.info#372]
**Describe the bug**  
Errormessage "/bin/sh: 1: hcitool: not found" upon start of the adapter.

**To Reproduce**  
1. Restart adapter
2. Have a look at the iobroker logs.

**Expected behavior**  
No error is thrown

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/2249766/140612608-d30a2482-4ea0-4bd0-9c82-5f0e40080e90.png)

**Versions:**  
 - Adapter version: 1.9.8
 - JS-Controller version: 3.3.18
 - Node version: 12.22.7
 - Operating system: docker -> buanet

**Additional context**

**Comment by Apollon77** [comment]
this is a part ogf the systeminformation that are collected and most likely a docker thing. Just disable the bluetooth data collection
