### ISSUE TITLE
State "web.0.info.connection" has no existing object, this might lead to an error in future versions

### ISSUE THREAD

**Issue by HansEhls** [iobroker-community-adapters/ioBroker.info#373]
**Describe the bug**  
Installation of iobroker in a VM on a Synology NAS

In the past I used the Iobroker on Raspi 4. Moved installation of iobroker in a VM on a Synology NAS and restored the backup there. 

The installation on a VM is done, because I did not get the TI Zigbee board running on the USB Port in a docker installation.

I control some lights and shutter with iobroker and Yahka with our iphones. 

Now i wanted to start with VIM and I read that i had to install web.0 before, so I did. that message came up directly after installation.

When I switch between the demo project and my first project, that message always comes up. Also when I do start the visualisation or stop the editor.

Thanks for your help.

BR
Hans

**Comment by Apollon77** [comment]
should be fixed in web already
