### ISSUE TITLE
Falscher Typ iface

### ISSUE THREAD

**Issue by JBSullivan** [iobroker-community-adapters/ioBroker.info#377]
Info Adapter Version 1 .9.16
Host 3.3.19

Heute nach dem Host Adapter Update tauchten erstmal die folgenden Meldungen auf.  Meine Vermutung geht in Richtung basic iframe, welches ich für den URL Aufruf von 4 Webcam rtsp Streams innerhalb der  vier verschiedenen iframes nutze.

<html>
<body>

info.0 | 2021-11-18 09:21:26.663 | info | State value to set for "info.0.sysinfo.network.interfaces.iface4.dhcp" has to be type "string" but received type "boolean"
-- | -- | -- | --
info.0 | 2021-11-18 09:21:26.596 | info | State value to set for "info.0.sysinfo.network.interfaces.iface3.dhcp" has to be type "string" but received type "boolean"
info.0 | 2021-11-18 09:21:26.522 | info | State value to set for "info.0.sysinfo.network.interfaces.iface2.dhcp" has to be type "string" but received type "boolean"
info.0 | 2021-11-18 09:21:26.346 | info | State value to set for "info.0.sysinfo.network.interfaces.iface0.dhcp" has to be type "string" but received type "boolean"

</body>
</html>

**Comment by Knallix** [comment]
Hallo,

habe auch immer noch diesen Fehler ... 

![LOG iobroker](https://user-images.githubusercontent.com/42406048/146685460-f2bcb207-b652-4eb5-83e0-849eaf36fddd.JPG)
