### ISSUE TITLE
Adapter uses too much CPU

### ISSUE THREAD

**Issue by EvilEls** [iobroker-community-adapters/ioBroker.info#38]
Pls reduce CPU usage

![image](https://user-images.githubusercontent.com/29343914/57707495-05f30600-7668-11e9-85e0-cee84ffc134e.png)

**Comment by ldittmar81** [comment]
You can control it. You can deactivate the cpu and ram data refresh time if you set it to 0 or take for example 10 seconds and the cpu usage will get lower.

**Comment by klassisch** [comment]
Yes thanks, there exists the possibility to ajust the refresh time. But it is limited to 10 seconds which still may cause trouble using small CPUs especially when using the "subscribe all to history" function. 
I would propose 
- extend the refresh time to bigger values like 30, 60, 120 seconds
- set the default values to the highest refresh times
- hook the "Don't load current system data" on as a default -> deactivate the function as a default
image with different settings just for reference
https://github.com/iobroker-community-adapters/ioBroker.info/blob/master/docs/en/img/config.png

**Comment by ldittmar81** [comment]
Now you can choose 240s. 
I set "Don't load current system data" as default true.
Default values are now higher.
I wrote a warning on the setup site: "Calling up current system data at too short intervals can lead to very high CPU consumption, especially under Windows. To switch off individual queries, set the slider to 0."

**Comment by klassisch** [comment]
Thanks a lot for the quick response an the great work! it really helps.
"To switch off individual queries, set the slider to 0." Perfect solution! More than I dared to hope for.
