### ISSUE TITLE
Infos sind Doppelt im Info Adapter sichtbar

### ISSUE THREAD

**Issue by dp20eic** [iobroker-community-adapters/ioBroker.info#380]
Guten Morgen,

Im Abschnitt "ioBroker Forum" werden mir die Meldungen zwei mal angezeigt, der original Text, ist der der auch im Forum angezeigt wird.

Ich zeige das mal an Screen Shots:

![image](https://user-images.githubusercontent.com/71387331/143676215-a2aebfb4-b6c4-4a4f-897e-50006f7c221c.png)

![image](https://user-images.githubusercontent.com/71387331/143676280-829464cb-53fe-4c60-b86e-6214de6ce04a.png)

Mein System:
PlatformBetriebssystem:linux
Architektur:x64
CPUs:2
Geschwindigkeit:3200 MHz
Modell:AMD Phenom(tm) II X4 955 Processor
RAM:3.5 GB
System-Betriebszeit:2 T. 00:20:44
Node.js:v17.0.1                         **<- das verhalten war auch schon so mit Node.js 12.x**
NPM:8.1.0
Datenträgergröße:12.0 GB
Festplatte frei:3.4 GB
Adapter-Anzahl:445
Betriebszeit:1 T. 14:45:02
Aktive Instanzen:26
Pfad:/opt/iobroker/

**Comment by dp20eic** [comment]
Guten Morgen,

bin ich der einzige mit diesem Verhalten?

VG
Bernd

**Comment by hydrotec468** [comment]
Guten Morgen Bernd, 
nein, siehe hier [[iobroker.info] Info "Zeige die neuesten Forumeinträge"](https://forum.iobroker.net/topic/47526/iobroker-info-info-zeige-die-neuesten-forumeintr%C3%A4ge) 
Gleiches Verhalten unter folgender Version. 
```
admin: v5.3.0
node: v14.19.0
npm: v6.14.16
js-controller: v4.0.12
info: v1.9.18
```
Gruß, Karsten

**Comment by dp20eic** [comment]
> Guten Morgen Bernd, nein, siehe hier [[iobroker.info] Info "Zeige die neuesten Forumeinträge"](https://forum.iobroker.net/topic/47526/iobroker-info-info-zeige-die-neuesten-forumeintr%C3%A4ge) Gleiches Verhalten unter folgender Version.
> 
> ```
> admin: v5.3.0
> node: v14.19.0
> npm: v6.14.16
> js-controller: v4.0.12
> info: v1.9.18
> ```
> 
> Gruß, Karsten

Danke, ich dachte schon ich bin zu blöd.
Na dann warten wir mal auf eine Aussage vom Entwickler :)

Viele Grüße
Bernd

**Comment by ldittmar81** [comment]
Der Entwickler sagt... Ähh... ok... muss ich nachschauen 🙈

**Comment by dp20eic** [comment]
Einen schönen guten Morgen :)

kann ja nicht wirklich sein, dass das nicht als Fehler eingestuft wird, oder sich einer der verantwortlichen dazu äußert.
Hoffe immer noch. das dies behoben wird.

VG
Bernd
