### ISSUE TITLE
Exception bei lesen der Bios Information in virtueller Maschine

### ISSUE THREAD

**Issue by SpikeNbg** [iobroker-community-adapters/ioBroker.info#44]
Hi!

Ich hab bei Verwendung des Info-Adapters folgendes Problem:
In meinem Log sehe ich eine Exception "ToLowerCase" of undefinded..
Getestet hab ich die 1.37 und auch die aktuellste Version hier (1.40)

Hab mal tiefer nachgesehen und der Fehler kommt aus der function bios(callback) in system.js

Mein ioBroker läuft auf einer QNAP virtuellen Maschine und beim Abfragen des Bios Release Date versucht er mittels "result.releaseDate = util.parseDateTime(datetime).date;" das Datum umzuwandeln. 
In meiner VM liefert jedoch die BIOS Information mittels "export LC_ALL=C; dmidecode --type 0 2>/dev/null; unset LC_ALL" den Wert "Not Specified"
Dabei kracht dann die Datumsumwandlung.

Evtl. muss hier eine andere Ermittlung statt finden oder einfach berücksichtigt werden, dass nicht immer ein Datum kommt.

Danke dir und beste Grüße
Ralf

**Comment by ldittmar81** [comment]
Hi... Kannst du bitte die aktuelle Version (1.4.2) mal testen und mir bescheid geben ob es jetzt funktioniert? Danke!

**Comment by SpikeNbg** [comment]
Hi!
Läuft jetzt ohne Exceptions!
Danke dir, ich mach zu.. :)
