### ISSUE TITLE
Handling of obsolete common.title 

### ISSUE THREAD

**Issue by mcm1957** [iobroker-community-adapters/ioBroker.info#474]
**Describe the bug**  
If an adapter does not specify common.title within io-broker.json the info field does not show any adapter name. See screenshot.

Note that the adapter checker already marks common.title as obsolete. Info adapter should use common.title-lang according to telegram discussion.

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/28575778/183244499-9cffe9dc-ecc8-489f-96d7-80bed1767792.png)

**Versions:**  
 - Adapter version: info 1.1.19

**Additional context**  
Telegram Context: (https://t.me/ioBroker_development/22449)

**Comment by klein0r** [comment]
The correct attribute for a translated adapter title is ``common.titleLang``.

https://github.com/ioBroker/ioBroker.js-controller/blob/0de381d6dcb68c48b2dcc14bb30672913bfd153b/schemas/io-package.json#L80-L83

**Comment by simatec** [comment]
Fix in v1.9.20
