### ISSUE TITLE
Fehler im Log

### ISSUE THREAD

**Issue by Ceel84** [iobroker-community-adapters/ioBroker.info#475]
`<html>
<body>

info.0 | 2022-08-25 11:20:17.005 | error | line is not defined
-- | -- | -- | --
info.0 | 2022-08-25 11:20:17.005 | error | ReferenceError: line is not defined at filterLines (/opt/iobroker/node_modules/systeminformation/lib/filesystem.js:66:9) at /opt/iobroker/node_modules/systeminformation/lib/filesystem.js:127:23 at ChildProcess.exithandler (node:child_process:390:7) at ChildProcess.emit (node:events:527:28) at ChildProcess.emit (node:domain:475:12) at maybeClose (node:internal/child_process:1092:16) at Socket.<anonymous> (node:internal/child_process:451:11) at Socket.emit (node:events:527:28) at Socket.emit (node:domain:475:12) at Pipe.<anonymous> (node:net:709:12)
info.0 | 2022-08-25 11:20:17.005 | error | uncaught exception: line is not defined

</body>
</html>`

**Comment by Apollon77** [comment]
fixed in next version
