### ISSUE TITLE
Information page is not displayed, activity bar is running forever

### ISSUE THREAD

**Issue by JojoS62** [iobroker-community-adapters/ioBroker.info#493]
**Describe the bug**  
Information page does not show content, the activity indicator is running forever. This happens with current git version 1.9.21, it was ok with 1.9.20. This can be reproduced by switching the adapter versions.

**To Reproduce**  
1. Go to 'info'
2. See error

**Expected behavior**  
show content as configured in info adapter

**Screenshots & Logfiles**  
on request

**Versions:**  
 - Adapter version: 1.9.21 bad, 1.9.20 ok
 - JS-Controller version: 4.0.23
 - Node version: v18.10.0, before the same problem with 14.x
 - Operating system: ubuntu 20.04

**Additional context**  
The debug log shows that the adapter is reading until docker information (docker is not installed, ioB is running in proxmox lxc).
The adapter itself is running and updating e.g. cpu load.

**Comment by danielgehlen** [comment]
Same here
buanet docker image on raspi
Node 16.18.1
iobroker 6.2.23

Info version 1.9.20 works fine, 1.9.21 and 1.9.22 the activity indicator is running forever.
This can be reproduced by switching the adapter versions.

**Comment by mpl1337** [comment]
same problem

log:

```
 <html>
<body>
<!--StartFragment-->

info.0 | 4040 | 2022-11-27 13:53:26.873 | error | Error: connect ECONNREFUSED 0.0.0.0:443
-- | -- | -- | -- | --


<!--EndFragment-->
</body>
</html>
```
