### ISSUE TITLE
Keine Anzeige ioBroker News

### ISSUE THREAD

**Issue by bergjet** [iobroker-community-adapters/ioBroker.info#50]
Es werden keine News angezeigt.
<img width="1421" alt="Screenshot 2019-08-02 15 15 51" src="https://user-images.githubusercontent.com/4241968/62373759-c1765880-b53a-11e9-8523-d06a66e0ec35.png">

**Comment by sigi2345** [comment]
Das ist bekannt..........

**Comment by ThomasBahn** [comment]
Macht es das besser?  ;-)

Liegt wohl daran, dass der RSS-Feed selbst wohl nicht mehr da ist?!
https://www.iobroker.net/docu/?feed=rss2&lang=de
ergibt: Cannot GET /docu/

Hat die der Betreiber der Web-Seite den Feed gekillt?

**Comment by ldittmar81** [comment]
Sorry... Ich komme zur Zeit echt nicht dazu irgendwas zu machen. Der neue Link sollte das hier sein: https://www.iobroker.net/blog_de.xml

Aber wie gesagt... Ich komme einfach nicht dazu es entsprechend anzupassen. 😞

**Comment by ThomasBahn** [comment]
Ich habe die Änderung in admin\lib\js\news.js gemacht, aber weiß nicht, wie man einen anständigen Pull Request macht. ;-(

Geändert habe ich nur eine Zeile (direkt nach dem try{):
```
async function readAndWriteNewsData() {
    if (adapterConfig.feednami) {
        feednami.setPublicApiKey(adapterConfig.feednami);
    }
    try {
        const rss = await feednami.load('http://www.iobroker.net/blog_' + newsLang + '.xml');
        writeNewsData(rss);
    } catch (e) {
        $('#newsListLoader').remove();
        if (e == "Error: Hostname in referer header is not registered") {
            $('#newsList').append($('<li>' + _("To read news or forum, you need a free API Key if your ioBroker installation can be reached via a hostname, such as iobroker: 8081 or something similar. For IP access it is not needed.") + '</li>'));
        } else {
            $('#newsList').append($('<li>' + e + '</li>'));
        }
    }
}
```

**Comment by ldittmar81** [comment]
Prinzipiell sieht es gut aus. Wenn jemand das kurz testen könnte und mir das ok gibt, dann mache ich die Änderung schnell rein. Soviel Zeit werde ich noch aufbringen können :-)

**Comment by ThomasBahn** [comment]
Da ich noch nicht weiß, wie man es richtig macht, habe ich die Änderung per "brute force" bei mir durchgeführt.

Die beschriebene Änderung in den Dateien
./iobroker-data/files/info.admin/lib/js/news.js
./node_modules/iobroker.info/admin/lib/js/news.js
gemacht, per
iobroker upload all
in den "Cache" geladen, meine info-Instant neu gestartet und den Browser-Cache geleert.

Jetzt sehe ich unten links den Feed mit 6 Artikeln.

Getestest mit deutsch, englisch und russisch.

**Comment by sigi2345** [comment]
> Wenn jemand das kurz testen könnte .........

Gerne, und wie?

**Comment by ldittmar81** [comment]
Alles gut :-) ... Ich habe es getestet und die neue Version 1.4.2 ist draußen!
