### ISSUE TITLE
Annoying note

### ISSUE THREAD

**Issue by rocklobster42195** [iobroker-community-adapters/ioBroker.info#51]
The note "Die Entwicklung geht weiter..." is really annoying and constantly pops up.
Best regards
Boris

**Comment by ldittmar81** [comment]
I know... sorry... it is a cache problem or so. I'm not sure where the problem is. The message should only be displayed once. :(

**Comment by ldittmar81** [comment]
https://github.com/ioBroker/ioBroker.admin/pull/421

First try

**Comment by ldittmar81** [comment]
Fixed with ioBroker admin 3.6.5
