### ISSUE TITLE
Info Adapter displays outdated infos as news

### ISSUE THREAD

**Issue by mickym2** [iobroker-community-adapters/ioBroker.info#516]
Currently the news in info adapter are more or less outdated: 

![image](https://user-images.githubusercontent.com/58858526/208405092-ee7e6143-5947-46fc-9cca-a7533a58664e.png)

Many articles are 1 year or older.

**Comment by mcm1957** [comment]
This outdated info is no problem of the adapter itself but results from missing new infos at https://www.iobroker.net/*/blog.
So this is not (primary) a issue of the adapter

BUT 

As a FEATURE request it would be nice to check whether info adapter could check the poublishing data and skip infos older then xxx months.

**Comment by mcm1957** [comment]
This adapter has been deprecated.

So most certainly this this issue will not be asolved anymore
