### ISSUE TITLE
[1.4.1] Hinweis auf neuere Node.js

### ISSUE THREAD

**Issue by DrBakterius** [iobroker-community-adapters/ioBroker.info#52]
Es wird die Node.js **v10.16.0** als neuere Version vorgeschlagen obwohl **v10.16.1** installiert ist!

![nodejs](https://user-images.githubusercontent.com/24896600/62538235-98afd500-b852-11e9-817b-4c4a28a73c13.jpg)

**Comment by ldittmar81** [comment]
Das ist ein Cache Problem. Die Liste aller existierenden Node Versionen wird einmal geladen und im Browser-Cache gehalten. Nach dem Browser-Neustart sollte es wieder richtig sein. Es kann aber auch sein, dass die neue Version raus gegangen ist, bevor es in der Node-Liste rein gekommen ist. Ich lese hier aber die originale Liste aus der Node.js Webseite. Sollte es also nicht passieren. Ich müsste vielleicht was einbauen, dass wenn die installierte Version > neuere Version, dann lade nochmal die Liste.

**Comment by m-s-b** [comment]
Ich hab ein ähnliches "Problem".
Habe node v10.16.3 installiert. und bekomme die Meldung:
Node.js v10.16.1 (Es gibt eine neuere Version: v10.16.3)
Neustart Adapter, iobroker haben nichts geholfen. Bei Slave wurde es nach dem zweiten reboot aktualisiert.

**Comment by ldittmar81** [comment]
Die Node.js Version kommt direkt vom js-controller. Hmm... komisch. Hat das Update auch funktioniert? Sind vielleicht 2 Node Versionen drauf?

**Comment by m-s-b** [comment]
Ja, das Update hat sauber funktioniert. Konnte auch keine Hinweise auf eine zweite Node Version finden. Zumal der Slave quasi fast jungfräulich frisch aufgesetzt war und selbiges anzeigte.
Hab jetzt nochmals  `iobroker restart` gemacht und erst jetzt zeigt er die richtige Version an.
Wie gesagt, eher ein "Schönheitsfehler" als ein wirklihces Problem.

**Comment by Diginix** [comment]
Bei mir wird seit gestern und inkl ioBroker Neustart das angezeigt:
Node.js v12.17.0 (Es gibt eine neuere Version: v12.16.3)

**Comment by mcm1957** [comment]
This adapter has been deprecated.

So most certainly this this issue will not be solved anymore
