### ISSUE TITLE
Log Größe in Adapter aufnehmen

### ISSUE THREAD

**Issue by sigi2345** [iobroker-community-adapters/ioBroker.info#53]
Hallo, gibt es einen DP in der man die Aktuelle Log Größe sehen kann?

Siehe:

https://forum.iobroker.net/topic/24472/log-gr%C3%B6%C3%9Fe-eigener-dp

**Comment by ldittmar81** [comment]
Mal sehen was möglich ist...

**Comment by sigi2345** [comment]
> Mal sehen was möglich ist...

News?

**Comment by ldittmar81** [comment]
Noch nicht... Ich schaue es mir als nächstes an :)
