### ISSUE TITLE
CPU Temperatur falsche Anzeige

### ISSUE THREAD

**Issue by sigi2345** [iobroker-community-adapters/ioBroker.info#57]
Temperatur wird falsch angezeigt.
V 1.5.4

![Screenshot (89)](https://user-images.githubusercontent.com/41079106/65759438-37520700-e11b-11e9-8a4a-17a73e0f5dc1.png)

**Comment by ldittmar81** [comment]
Hat es vorher funktioniert? Was für ein Betriebssystem?

**Comment by sigi2345** [comment]
> Hat es vorher funktioniert? Was für ein Betriebssystem? Gibt es irgendwie ein Fehler in der Browser Console?

Ja, Windows 10 , Nein

**Comment by ldittmar81** [comment]
Ohh ja... hmm... kannst du noch bitte auf die einzelnen temperature.main Links klicken und mir zeigen wo die Fehler auftreten? Du müsstest dann direkt zu einer Code-Zeile springen.

**Comment by sigi2345** [comment]
> Ohh ja... hmm... kannst du noch bitte auf die einzelnen temperature.main Links klicken und mir zeigen wo die Fehler auftreten? Du müsstest dann direkt zu einer Code-Zeile springen.

...bekomme die Fehlermeldung nicht mehr.

Zur Info: Es wurde der Neue js-controller 2.x installiert!
![Screenshot (103)](https://user-images.githubusercontent.com/41079106/65785932-d136a580-e155-11e9-9784-d61e6e924ba9.png)

**Comment by sigi2345** [comment]
Fehler ist noch da, gibt es was neues dazu?

**Comment by ldittmar81** [comment]
Ahhh.... jetzt habe ich endlich verstanden warum du da ein Fehler bekommst. Dein Host hat Klammern im Namen!! :see_no_evil: Also Medion(Smarthome) - ahh.... :laughing: :sob:

**Comment by ldittmar81** [comment]
Bitte die aktuelle Git Version 1.5.6 testen

**Comment by sigi2345** [comment]
> Bitte die aktuelle Git Version 1.5.6 testen

Keine Änderung

**Comment by sigi2345** [comment]
> Also Medion(Smarthome) - ahh....

Dieser wurde vom Windows Installer vergeben.
https://forum.iobroker.net/topic/24647/aufruf-iobroker-f%C3%BCr-windows-version-1-5-14

**Comment by ldittmar81** [comment]
Ich meine erstmal, ob die roten Fehlermeldungen noch erscheinen? Das müsste mit dem letzten Fix korrigiert worden sein. Sollten jetzt noch js Meldungen kommen, dann bitte hier erneut posten, damit ich es analidieren kann.

**Comment by sigi2345** [comment]
> Ich meine erstmal, ob die roten Fehlermeldungen noch erscheinen?

Nein,  Danke.

Kerne 4 °C ?
CPU Temp    Keine

![Screenshot (272)](https://user-images.githubusercontent.com/41079106/66806014-bbcbc480-ef26-11e9-90ba-d8f752484b22.png)

**Comment by aleks-83** [comment]
Bei mir sieht es genau so aus.
Im Info Adapter steht **4°C**, in den Datenpunkten steht in jedem Kern **-1°C**

Win 10.0.18362
Celeron® J3455
JS 2.0.39
Info 1.5.6

**Comment by sigi2345** [comment]
Anzeige Plötzlich wieder da!

**Comment by aleks-83** [comment]
Hängts evtl mit der Version vom JS Controller zusammen?
Bei meinem System mit JS Controller 2.1.1 funktioniert es (noch) nicht.

**Comment by sigi2345** [comment]
Noch immer keine Grafik.

**Comment by ldittmar81** [comment]
> Noch immer keine Grafik.

Hmm... Fehlermeldung in der Browser Konsole?

**Comment by sigi2345** [comment]
> > Noch immer keine Grafik.
> 
> Hmm... Fehlermeldung in der Browser Konsole?

Nein

**Comment by sigi2345** [comment]
CPU Temp Fehler wieder da!
Anzeige -1 Grad
Version 1.7.14



Platform: Windows
RAM: 16 GB 
Node.js: v12.20.0
NPM: 6.14.8
JS Controler: 3.1.6
Admin: 4.1.12
Web: 3.1.0
Socket.io: 3.0.13
Script Engine: 4.10.8
IOT: 1.8.8
VIS: 1.3.6
