### ISSUE TITLE
Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by DerGrafausB** [iobroker-community-adapters/ioBroker.info#59]
host.ioBroker | 2019-10-09 19:21:20.863 | error | instance system.adapter.info.0 terminated with code 0 (OK)
-- | -- | -- | --
Caught | 2019-10-09 19:21:20.863 | error | by controller[0]: at Manager.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
Caught | 2019-10-09 19:21:20.863 | error | by controller[0]: at Socket.onpacket (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:236:12)
Caught | 2019-10-09 19:21:20.863 | error | by controller[0]: at Socket.onack (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:312:9)
Caught | 2019-10-09 19:21:20.863 | error | by controller[0]: at Socket.adapter.objects.getObjectView (/opt/iobroker/node_modules/iobroker.info/main.js:191:21)
Caught | 2019-10-09 19:21:20.863 | error | by controller[0]: at instances (/opt/iobroker/node_modules/iobroker.info/main.js:92:26)
Caught | 2019-10-09 19:21:20.863 | error | by controller[0]: at Array.forEach (<anonymous>)
Caught | 2019-10-09 19:21:20.863 | error | by controller[0]: at messages.forEach.message (/opt/iobroker/node_modules/iobroker.info/main.js:103:57)
Caught | 2019-10-09 19:21:20.863 | error | by controller[0]: at Array.forEach (<anonymous>)
Caught | 2019-10-09 19:21:20.863 | error | by controller[0]: at Object.keys.forEach.key (/opt/iobroker/node_modules/iobroker.info/main.js:124:49)
Caught | 2019-10-09 19:21:20.863 | error | by controller[0]: at checkVersion (/opt/iobroker/node_modules/iobroker.info/main.js:150:23)
Caught | 2019-10-09 19:21:20.863 | error | by controller[0]: TypeError: Cannot read property 'split' of undefined
info.0 | 2019-10-09 19:21:20.849 | error | uncaught exception: Cannot read property 'split' of undefined

**Comment by ldittmar81** [comment]
You can try the Github Version 1.5.5 of Info. The error should be fixed there.

**Comment by DerGrafausB** [comment]
I have got

Information tab

Verfügbare Version:1.4.3
Installierte Version:1.4.3


don't exist 1.5.5

npm install iobroker.info@1.5.5
npm ERR! code ETARGET
npm ERR! notarget No matching version found for iobroker.info@1.5.5
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-10-10T16_12_18_707Z-debug.log

**Comment by ldittmar81** [comment]
On npm, only version 1.5.4 is available. If you want to install the 1.5.5, you have to instal directly over Github. You have to click on the button with the cat in the ioBroker under adapters.

**Comment by DerGrafausB** [comment]
ok, 1.5.5 is installed.

Same Problem


host.ioBroker | 2019-10-10 20:48:52.019 | error | instance system.adapter.info.0 terminated with code 0 (OK)
-- | -- | -- | --
Caught | 2019-10-10 20:48:52.016 | error | by controller[0]: at Socket.onpacket (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:236:12)
Caught | 2019-10-10 20:48:52.016 | error | by controller[0]: at Socket.onack (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:312:9)
Caught | 2019-10-10 20:48:52.016 | error | by controller[0]: at Socket.adapter.objects.getObjectView (/opt/iobroker/node_modules/iobroker.info/main.js:258:21)
Caught | 2019-10-10 20:48:52.016 | error | by controller[0]: at instances (/opt/iobroker/node_modules/iobroker.info/main.js:158:26)
Caught | 2019-10-10 20:48:52.016 | error | by controller[0]: at Array.forEach (<anonymous>)
Caught | 2019-10-10 20:48:52.016 | error | by controller[0]: at messages.forEach.message (/opt/iobroker/node_modules/iobroker.info/main.js:170:57)
Caught | 2019-10-10 20:48:52.016 | error | by controller[0]: at Array.forEach (<anonymous>)
Caught | 2019-10-10 20:48:52.016 | error | by controller[0]: at Object.keys.forEach.key (/opt/iobroker/node_modules/iobroker.info/main.js:183:46)
Caught | 2019-10-10 20:48:52.016 | error | by controller[0]: at checkConditions (/opt/iobroker/node_modules/iobroker.info/main.js:136:25)
Caught | 2019-10-10 20:48:52.016 | error | by controller[0]: at checkVersion (/opt/iobroker/node_modules/iobroker.info/main.js:217:23)
Caught | 2019-10-10 20:48:52.016 | error | by controller[0]: TypeError: Cannot read property 'split' of undefined
info.0 | 2019-10-10 20:48:52.007 | info | cleaned everything up...
info.0 | 2019-10-10 20:48:52.006 | error | at Socket.onpacket (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:236:12)
info.0 | 2019-10-10 20:48:52.006 | error | at Socket.onack (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:312:9)
info.0 | 2019-10-10 20:48:52.006 | error | at Socket.adapter.objects.getObjectView (/opt/iobroker/node_modules/iobroker.info/main.js:258:21)
info.0 | 2019-10-10 20:48:52.006 | error | at instances (/opt/iobroker/node_modules/iobroker.info/main.js:158:26)
info.0 | 2019-10-10 20:48:52.006 | error | at Array.forEach (<anonymous>)
info.0 | 2019-10-10 20:48:52.006 | error | at messages.forEach.message (/opt/iobroker/node_modules/iobroker.info/main.js:170:57)
info.0 | 2019-10-10 20:48:52.006 | error | at Array.forEach (<anonymous>)
info.0 | 2019-10-10 20:48:52.006 | error | at Object.keys.forEach.key (/opt/iobroker/node_modules/iobroker.info/main.js:183:46)
info.0 | 2019-10-10 20:48:52.006 | error | at checkConditions (/opt/iobroker/node_modules/iobroker.info/main.js:136:25)
info.0 | 2019-10-10 20:48:52.006 | error | at checkVersion (/opt/iobroker/node_modules/iobroker.info/main.js:217:23)
info.0 | 2019-10-10 20:48:52.006 | error | TypeError: Cannot read property 'split' of undefined
info.0 | 2019-10-10 20:48:52.006 | error | uncaught exception: Cannot read property 'split' of undefined
