### ISSUE TITLE
TypeError: Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by valbuz** [iobroker-community-adapters/ioBroker.info#62]
Hy

Since 3 days, this error all the time
i can't see from which adapter

is there any hint's?

thanks
pat

**Comment by ldittmar81** [comment]
Hi. I need more informations: Which version did you install? Operating system? Admin version? JS controller version?

**Comment by valbuz** [comment]
Sorry, i'm new...

Version: 1.4.3
Linux
Admin: 3.6.7
JS: 10.16.3

thanks
pat
