### ISSUE TITLE
Data point as JSON for all events

### ISSUE THREAD

**Issue by DutchmanNL** [iobroker-community-adapters/ioBroker.info#63]
Please add an datapoint to the info-structure tree which allows us to see the Curren Event dat as JSON string.
This would allow users to adopt the table into their own vis.

I would like to see 3 datapoints for events

- Full overview of events as JSON (or HTML or even both what's beter for VIS ?)
- Datapoint : Event currently present (true/false)
- Next scheduled event (Name, date/time

**Comment by mcm1957** [comment]
This adapter has been deprecated.

So most certainly this this issue will not be solved anymore
