### ISSUE TITLE
Darstellung im Darkmode

### ISSUE THREAD

**Issue by Boronsbruder** [iobroker-community-adapters/ioBroker.info#645]
![grafik](https://github.com/ioBroker/ioBroker.admin/assets/35029874/a72d0160-d8b6-4ea2-8616-3a707c9f8444)
Im Darkmode ist die Darstellung der hervorgehobenen Punkte extrem  schlecht lesbar.
Könnte man da was ändern?

Getestet in Chrome und Firefox im Admin v6.10.1

![grafik](https://github.com/ioBroker/ioBroker.admin/assets/35029874/fdbda513-e7ce-4701-a021-d146436d79c9)
Ach ja und vielleicht die farbliche Hervorhebung wie in den hellen Themen übernehmen

**Comment by Diginix** [comment]
Den Text in der Infobox kann man im Darkmode gar nicht lesen:

![image](https://github.com/iobroker-community-adapters/ioBroker.info/assets/39678667/360fc391-35ce-435d-8018-41a019bfcc39)

info: 2.0.0
admin: 6.13.15
node.js: 18.19.0
js-controller: 5.0.17

**Comment by mcm1957** [comment]
This adapter has been deprecated.

So most certainly this this issue will not be asolved anymore
