### ISSUE TITLE
Disabling the watch leads to error messages

### ISSUE THREAD

**Issue by drtp** [iobroker-community-adapters/ioBroker.info#68]
Hi,

I just tested this adapter and tried to disable the watch. However, it was not possible and I obtaines serveral error messages within the log. I use the latest version of all installed adapters includind admin und js-controller.

In addition, my ioBroker runs within a Docker-Container on a Synology DiskStation.

Regards,

Thorsten

**Comment by ldittmar81** [comment]
Can you post the error messages? That could be helpful. I was not able to reproduce this bug.

**Comment by Apollon77** [comment]
no reaction, closed
