### ISSUE TITLE
Fehlermeldung: Cannot read property 'split' of undefined ...

### ISSUE THREAD

**Issue by Harry-58** [iobroker-community-adapters/ioBroker.info#69]
Habe heute im Log entdeckt, dass der Info-Adapter Probleme hat.
Im Minutenabstand werden Fehlermeldungen geschrieben.
Vor einer Woche war der Fehler definitiv noch nicht vorhanden.
Mein System: ioBroker auf Raspberry 4 mit 2GB Speicher.
Alle Adapter auf aktuellem Stand (stable) 
RasPi ist ebenfalls auf aktuellem Stand.
Es wurde außer den Updates keine neuen Adapter installiert.
Info-Adapter habe ich auch schon gelöscht und neu installiert, hat aber nix gebracht.
Die anderen Issues zum gleichen Thema habe ich gelesen, aber der Fehler scheint auch in der aktuellen Stable.Version 1.5.6 noch zu bestehen.
Habe zum Test auch aus Github 1.5.7 installiert --> gleiches Problem

Hier die Fehlermeldungen:
    host.iobroker	2020-02-07 17:45:29.827	info	Restart adapter system.adapter.info.0 because enabled
    host.iobroker	2020-02-07 17:45:29.827	info	instance system.adapter.info.0 terminated with code 0 (NO_ERROR)
    host.iobroker	2020-02-07 17:45:29.827	error	Caught by controller[0]: at tryCatcher (/opt/iobroker/node_modules/standard-as-callback/built/utils.js:11:23)
    host.iobroker	2020-02-07 17:45:29.827	error	Caught by controller[0]: at (anonymous function).(anonymous function) (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/iobroker.objects-redis/index.js:17:90593)
    host.iobroker	2020-02-07 17:45:29.827	error	Caught by controller[0]: at adapter.objects.getObjectView (/opt/iobroker/node_modules/iobroker.info/main.js:264:21)
    host.iobroker	2020-02-07 17:45:29.827	error	Caught by controller[0]: at instances (/opt/iobroker/node_modules/iobroker.info/main.js:160:26)
    host.iobroker	2020-02-07 17:45:29.826	error	Caught by controller[0]: at Array.forEach (<anonymous>)
    host.iobroker	2020-02-07 17:45:29.826	error	Caught by controller[0]: at messages.forEach.message (/opt/iobroker/node_modules/iobroker.info/main.js:172:57)
    host.iobroker	2020-02-07 17:45:29.826	error	Caught by controller[0]: at Array.forEach (<anonymous>)
    host.iobroker	2020-02-07 17:45:29.826	error	Caught by controller[0]: at Object.keys.forEach.key (/opt/iobroker/node_modules/iobroker.info/main.js:185:46)
    host.iobroker	2020-02-07 17:45:29.826	error	Caught by controller[0]: at checkConditions (/opt/iobroker/node_modules/iobroker.info/main.js:138:25)
    host.iobroker	2020-02-07 17:45:29.825	error	Caught by controller[0]: at checkVersion (/opt/iobroker/node_modules/iobroker.info/main.js:223:23)
    host.iobroker	2020-02-07 17:45:29.825	error	Caught by controller[0]: TypeError: Cannot read property 'split' of undefined
    info.0	2020-02-07 17:45:29.304	info	(7573) Terminated (NO_ERROR): Without reason
    info.0	2020-02-07 17:45:29.303	info	(7573) terminating
    info.0	2020-02-07 17:45:29.293	info	(7573) cleaned everything up...
    info.0	2020-02-07 17:45:29.291	error	(7573) TypeError: Cannot read property 'split' of undefined at checkVersion (/opt/iobroker/node_modules/iobroker.info/main.js:223:23) at checkConditions (/opt/iobroker/node_modules/iobroker.in
    info.0	2020-02-07 17:45:29.290	error	(7573) uncaught exception: Cannot read property 'split' of undefined
    info.0	2020-02-07 17:45:29.131	info	(7573) Popup news was read...
    info.0	2020-02-07 17:45:27.624	info	(7573) starting. Version 1.5.6 in /opt/iobroker/node_modules/iobroker.info, node: v10.19.0

**Comment by Hesse-Bub** [comment]
Ich habe bei mir das gleiche Problem

**Comment by Harry-58** [comment]
Habe das Problem noch etwas weiter untersucht.
Verursacher ist der Web-Adapter in Version 2.4.10 (Stable-Version)
Wenn die Version dieses Adapters im Info-Adapter in  main.js  "checkVersion" geprüft wird,
steht  der Parameter "smalller" auf "undefined"
Da dieser Fehler nicht abgefangen ist, bricht Info ab.
Nach update des Web-Adapters auf 3.0.0 aus Github war das Problem behoben.
Trotzdem sollte im Info-Adapter auf "undefined" geprüft werden, da sonst der Fehler immer wieder vorkommen kann.
