### ISSUE TITLE
Meldungen als gelesen markieren

### ISSUE THREAD

**Issue by ldittmar81** [iobroker-community-adapters/ioBroker.info#70]
Die Meldungen im Info-Adapter können zur Zeit nicht ausgeblendet werden. Ein Button "Gelesen und verstanden" soll implementiert werden. Mein Klick verschwindet die Meldung für immer.

**Comment by JojoS62** [comment]
villeicht wie beim OctoPi implementieren? Es gibt da zwei Buttons: 'später lesen': Meldung verschwindet, kommt aber beim nächsten Aufruf wieder. 'gelesen': Meldung weg und kommt nicht wieder.

**Comment by ldittmar81** [comment]
Fixed with 1.7.2
