### ISSUE TITLE
Last Error anzeigen

### ISSUE THREAD

**Issue by Chaot1** [iobroker-community-adapters/ioBroker.info#80]
Gibt es eine Möglichkeit ein Fenster anzulegen in dem der letzte (oder die letzten n Fehler) angezeigt werden.
Das könnte schneller sein als die separat aus dem Log herauszusuchen.
Gerade wenn man wie ich den Info Tab als Startseite verwendet sieht man so mit einem Blick was gerade an Fehlern angefallen ist.

**Comment by ldittmar81** [comment]
Die Idee ist gut. Sobald ich mal wieder etwas Luft habe, schaue ich mal nach wie das zu machen ist.

**Comment by mcm1957** [comment]
This adapter has been deprecated.

So most certainly this this issue will not be solved anymore
