### ISSUE TITLE
Empfohlene Nodejs ist "10.x", sollte aber "12.x" sein?

### ISSUE THREAD

**Issue by mswiege** [iobroker-community-adapters/ioBroker.info#81]
In https://forum.iobroker.net/topic/32481/js-controller-3-0-jetzt-im-latest hat apollon77 geschrieben, dass mit js-controller 3.x nun 12.x die empfohlende Node Version ist:
`Wir werden mit diesem Release auch die empfohlene Node.js Version für ioBroker auf 12.x anheben.`
Ich bin nun auf js-controller 3.x und nodejs 12.16.2, aber der Info Adapter zeigt das "veraltete" `(Empfohlene Version v10.20.1)` an.

**Comment by ldittmar81** [comment]
Ziel wird es sein den 12er als empfohlen und den 8er raus zu werfen. Ich warte noch auf das GO von oben ;-)

**Comment by ldittmar81** [comment]
Done
