### ISSUE TITLE
Link to an internal site instead of github.

### ISSUE THREAD

**Issue by Anzic23** [iobroker-community-adapters/ioBroker.info#82]
**Describe the bug**  
if you try to open the link in the driver description, you will end up on a non-existent page.
**To Reproduce**  
1. Go to info tab
2. Click on icon with description
3. Click on Changelog

**Expected behavior**  
Opening a link from github, not from my site.

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/37106885/80336290-8f8eea00-885f-11ea-996a-a982a23175ed.png)

**Versions:**  
 - Adapter version: 1.7.0 (the error was present on previous versions as well.)
 - JS-Controller version: 3.0.18 (the error was present on previous versions as well.)
 - Node version: v12.16.2 (the error was present on previous versions as well.)
 - Operating system: linux

**Comment by mcm1957** [comment]
This adapter has been deprecated.

So most certainly this this issue will not be asolved anymore
