### ISSUE TITLE
ich habe diese Meldung:  (1348) adapter.objects.getObjectView is deprecated, and will be removed in the future. Please use adapter.getObjectView/Async. Report this to Developer!

### ISSUE THREAD

**Issue by h2okopfmt** [iobroker-community-adapters/ioBroker.info#84]
ich habe diese Meldung :
(1348) adapter.objects.getObjectView is deprecated, and will be removed in the future. Please use adapter.getObjectView/Async. Report this to Developer!

**Comment by Apollon77** [comment]
should be fixed
