### ISSUE TITLE
Documentation languages, Iobroker adapters on Github.

### ISSUE THREAD

**Issue by Anzic23** [iobroker-community-adapters/ioBroker.info#85]
the check box is not set in the documentation languages.
![image](https://user-images.githubusercontent.com/37106885/81375399-19656f80-910a-11ea-8a3b-fdb4ccb3cf9f.png)

IoBroker adapters don't load on Github
![image](https://user-images.githubusercontent.com/37106885/81375374-0a7ebd00-910a-11ea-9e05-da406abc83cf.png)

when you try to insert an image, the following text is inserted `![](http://)`

---

**System data:**

Platform: linux
Distribution: Debian GNU/Linux
Architecture: x64
Model: Intel(R) Celeron(R) CPU G1610T @ 2.30GHz
RAM: 9.73 GB
Node.js: v12.16.2
NPM: 6.14.4
Model: ARMv7 Processor rev 4 (v7l)
RAM: 975.61 MB
Node.js: v12.16.2
NPM: 6.14.4
JS-Controller (1): 3.0.20
Admin: 4.1.1
Information tab: 1.7.2

> *created by ioBroker.info*

**Comment by mcm1957** [comment]
This adapter has been deprecated.

So most certainly this this issue will not be asolved anymore
