### ISSUE TITLE
ioBroker-Adapter auf Github

### ISSUE THREAD

**Issue by detafun** [iobroker-community-adapters/ioBroker.info#93]
Hallo,
in der aktuellen Version, war auch in den Versionen davor so, das es irgendwann nicht mehr funktionierte.
"ioBroker-Adapter auf Github"
Es kommt nur immer in diesem Feld der Kreis der Läuft und Läuft.  
Alles andere funktioniert einwandfrei.
Im Log steht kein Fehler..

cu Deta

**Comment by ldittmar81** [comment]
Wenn du im Browser F12 klickst, erscheint die Browser Console. Wenn du dann den Info Tab öffnest, kommen dann dort Fehlermeldungen?

**Comment by detafun** [comment]
Weis nicht ob das das ist:
Access to fetch at 'https://api.github.com/search/repositories?q=iobroker+in:name&sort=updated&page=10&per_page=100' from origin 'http://rock:8081' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
api.github.com/search/repositories?q=iobroker+in:name&sort=updated&page=10&per_page=100:1 Failed to load resource: net::ERR_FAILED

kommt ja der Sorcecode mit diversen Infos.

**Comment by ldittmar81** [comment]
Gleiches Problem wie in #85 -> Wird dort gefixt werden
